### ISSUE TITLE
Add test coverage

### ISSUE THREAD

**Issue by arkgast** [MarketProject/Dapp#32]
Since the test environment is setup as a next step we can implement test coverage to improve the existing test and write a better ones.

## Tasks to do
- [x] Configure jest coverage options.
- [x] Connect with https://coveralls.io.
- [ ] Improve and write new tests to achieve at least 90% of coverage.

![img](https://cdn.pbrd.co/images/H6XE2nC.png)

> This is the current report, all numbers should be green colored.

**Comment by pelsasser** [comment]
Hey @arkgast - still planning on fleshing out this issue a bit more? Happy to stake it once you have

**Comment by arkgast** [comment]
Yeah, totally. Today I'll work on this issue.

**Comment by pelsasser** [comment]
@arkgast - how is this progressing?

**Comment by pelsasser** [comment]
@vivek any progress on tracking this issue down with the gitcoin bounty?

**Comment by pelsasser** [comment]
Would like to open this up to anyone to work on since haven't heard from @arkgast in a bit.  Feel free to jump in

**Comment by perfectmak** [comment]
This should be straight forward to do. Let me try and quickly get this closed.

**Comment by gitcoinbot** [comment]
__Work has been started on the 0.25 ETH (240.84 USD) funding by__: 
 1. [@perfectmak](https://gitcoin.co/profile/perfectmak) 

 __Please work together__ and coordinate delivery of the issue scope. Gitcoin doesn't know enough about everyones skillsets / free time to say who should work on what, but we trust that the community is smart and well-intentioned enough to work together.  As a general rule; if you start work first, youll be at the top of the above list ^^, and should have 'dibs' as long as you follow through. 

 On the above list? Please leave a comment to let the funder (@pelsasser) and the other parties involved what you're working, with respect to this issue and your plans to resolve it.  If you don't leave a comment, the funder may expire your submission at their discretion. 

 * Learn more [on the gitcoin issue page](https://gitcoin.co/funding/details?url=https://github.com/MarketProject/Dapp/issues/32)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $12355.42 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by gitcoinbot** [comment]
__This issue now has a funding of 0.25 ETH (234.7 USD) attached to it.__

 * If you would like to work on this issue you can claim it [here](https://gitcoin.co/funding/details?url=https://github.com/MarketProject/Dapp/issues/32).
 * If you've completed this issue and want to claim the bounty you can do so [here](https://gitcoin.co/funding/details?url=https://github.com/MarketProject/Dapp/issues/32)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $10256.78 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by gitcoinbot** [comment]
__Work has been started on the 0.25 ETH (234.84 USD) funding by__: 
 1. [@perfectmak](https://gitcoin.co/profile/perfectmak) 

 __Please work together__ and coordinate delivery of the issue scope. Gitcoin doesn't know enough about everyones skillsets / free time to say who should work on what, but we trust that the community is smart and well-intentioned enough to work together.  As a general rule; if you start work first, youll be at the top of the above list ^^, and should have 'dibs' as long as you follow through. 

 On the above list? Please leave a comment to let the funder (@pelsasser) and the other parties involved what you're working, with respect to this issue and your plans to resolve it.  If you don't leave a comment, the funder may expire your submission at their discretion. 

 * Learn more [on the gitcoin issue page](https://gitcoin.co/funding/details?url=https://github.com/MarketProject/Dapp/issues/32)
 * Questions? Get help on the <a href='https://gitcoin.co/slack'>Gitcoin Slack</a>
 * $10150.28 more Funded OSS Work Available at: https://gitcoin.co/explorer

**Comment by perfectmak** [comment]
I tried submitting this work on gitcoin too, but for some reason, it [failed](https://etherscan.io/tx/0x1c4095675686039e1f1ce7e741ae773823a8b057aeb7f7b2919792ab5adab5af).
It keeps failing everytime I try. Really don't know why this happens.

**Comment by pelsasser** [comment]
@perfectmak - I think they changed they way things are expiring.  Working to get you payment now, will make bounties in the future have a longer expiration
